import {DEFECT_CATALOGUE_ENTRIES} from "./defect_catalogue_data";

/**
 * One row of the controlled, authoritative defect catalogue — Main
 * Element -> Component -> Defect Description -> Suggested Corrective
 * Action, transcribed from "DEFECT_REPORT_LIST.xlsx - DEFECT LIST.pdf"
 * (see tool/generate_defect_catalogue.py at the repo root, the single
 * source of truth for both this and the Flutter-side copy).
 *
 * The AI provider selects an entry by `id` — it never invents a main
 * element, component, defect, or corrective action; the corrective
 * action is always resolved from here server-side, never generated by
 * the model itself.
 */
export interface DefectCatalogueEntry {
  /** Stable, globally-unique id — currently equal to `defectId`. */
  id: string;
  mainElementId: string;
  mainElementName: string;
  componentId: string;
  componentName: string;
  /** Same value as `id` today — see `id`'s doc comment. */
  defectId: string;
  defectDescription: string;
  /**
   * The controlled, predefined corrective action text. `null` only
   * where the source document itself left this cell blank (a couple of
   * "Sanitary Fitting -> Shower Head" rows) — preserved as an honest
   * gap rather than invented wording.
   */
  correctiveAction: string | null;
}

export interface DefectCatalogueMainElement {
  id: string;
  name: string;
}

export interface DefectCatalogueComponent {
  id: string;
  name: string;
  mainElementId: string;
}

const EMPTY_MAIN_ELEMENTS: Record<string, string> = {
  furniture: "Furniture",
  others: "Others",
};

/**
 * Queryable wrapper around `DEFECT_CATALOGUE_ENTRIES` — the gateway
 * should go through this rather than searching the raw list directly.
 */
class DefectCatalogueIndex {
  readonly entries: DefectCatalogueEntry[];
  readonly mainElements: DefectCatalogueMainElement[];
  readonly components: DefectCatalogueComponent[];
  private readonly byId: Map<string, DefectCatalogueEntry>;
  private readonly byComponent: Map<string, DefectCatalogueEntry[]>;
  private readonly byMainElement: Map<string, DefectCatalogueEntry[]>;

  /** @param {DefectCatalogueEntry[]} entries the flat catalogue rows. */
  constructor(entries: DefectCatalogueEntry[]) {
    this.entries = entries;
    this.byId = new Map(entries.map((e) => [e.id, e]));
    this.byComponent = groupBy(entries, (e) => e.componentId);
    this.byMainElement = groupBy(entries, (e) => e.mainElementId);

    const mainElementIds: string[] = [];
    const mainElementNames = new Map<string, string>();
    const componentsById = new Map<string, DefectCatalogueComponent>();
    for (const e of entries) {
      if (!mainElementNames.has(e.mainElementId)) {
        mainElementIds.push(e.mainElementId);
        mainElementNames.set(e.mainElementId, e.mainElementName);
      }
      if (!componentsById.has(e.componentId)) {
        componentsById.set(e.componentId, {
          id: e.componentId,
          name: e.componentName,
          mainElementId: e.mainElementId,
        });
      }
    }
    for (const [id, name] of Object.entries(EMPTY_MAIN_ELEMENTS)) {
      if (!mainElementNames.has(id)) {
        mainElementIds.push(id);
        mainElementNames.set(id, name);
      }
    }
    this.mainElements = mainElementIds.map((id) => ({
      id,
      name: mainElementNames.get(id) as string,
    }));
    this.components = Array.from(componentsById.values());
  }

  /**
   * @param {string} id a catalogue entry id.
   * @return {DefectCatalogueEntry | undefined} the entry, if it exists.
   */
  getById(id: string): DefectCatalogueEntry | undefined {
    return this.byId.get(id);
  }

  /**
   * @param {string} id a catalogue entry id, typically from an AI
   *   response that must never be trusted blindly.
   * @return {boolean} whether `id` is a real, known catalogue entry.
   */
  isValidEntryId(id: string): boolean {
    return this.byId.has(id);
  }

  /**
   * @param {string} componentId a component id.
   * @return {DefectCatalogueEntry[]} every defect entry under it.
   */
  forComponent(componentId: string): DefectCatalogueEntry[] {
    return this.byComponent.get(componentId) ?? [];
  }

  /**
   * @param {string} mainElementId a main element id.
   * @return {DefectCatalogueEntry[]} every defect entry under it.
   */
  forMainElement(mainElementId: string): DefectCatalogueEntry[] {
    return this.byMainElement.get(mainElementId) ?? [];
  }
}

/**
 * Groups `items` by a derived key, preserving each group's original
 * relative order.
 * @param {T[]} items the items to group.
 * @param {Function} keyOf the grouping key function.
 * @return {Map<string, T[]>} items grouped by key.
 */
function groupBy<T>(
  items: T[],
  keyOf: (item: T) => string
): Map<string, T[]> {
  const result = new Map<string, T[]>();
  for (const item of items) {
    const key = keyOf(item);
    const group = result.get(key);
    if (group) {
      group.push(item);
    } else {
      result.set(key, [item]);
    }
  }
  return result;
}

export const defectCatalogue = new DefectCatalogueIndex(
  DEFECT_CATALOGUE_ENTRIES
);
