import 'defect_catalogue_data.dart';

/// One row of the controlled, authoritative defect catalogue —
/// Main Element -> Component -> Defect Description -> Suggested
/// Corrective Action, transcribed from "DEFECT_REPORT_LIST.xlsx -
/// DEFECT LIST.pdf" (see `tool/generate_defect_catalogue.py`, the
/// single source of truth for both this and the Functions-side copy).
///
/// AI selects a [DefectCatalogueEntry] by [id] — it never invents a
/// main element, component, defect, or corrective action; the
/// corrective action is always resolved from here, never generated by
/// the AI provider itself. See `docs/ai_provider_architecture.md`
/// ("Controlled defect catalogue").
class DefectCatalogueEntry {
  const DefectCatalogueEntry({
    required this.id,
    required this.mainElementId,
    required this.mainElementName,
    required this.componentId,
    required this.componentName,
    required this.defectId,
    required this.defectDescription,
    required this.correctiveAction,
    this.isCustom = false,
  });

  /// True for an entry the user's own company added (never part of the
  /// ProDefact master catalogue). Custom entries are visible only to the
  /// account that created them.
  final bool isCustom;

  /// Stable, globally-unique id for this entry — currently equal to
  /// [defectId] (one catalogue row per defect description), kept as a
  /// separate field so a future catalogue revision could distinguish
  /// them without a breaking rename.
  final String id;

  final String mainElementId;
  final String mainElementName;

  final String componentId;
  final String componentName;

  /// Same value as [id] today — see [id]'s doc comment.
  final String defectId;

  final String defectDescription;

  /// The controlled, predefined corrective action text. `null` only
  /// where the source document itself left this cell blank (a few
  /// "Sanitary Fitting -> Shower Head" rows) — preserved as an honest
  /// gap rather than inventing wording; the UI/report must handle a
  /// null corrective action explicitly rather than assume it's always
  /// present.
  final String? correctiveAction;
}

/// A main element that exists in the catalogue but currently has no
/// components/defects defined (e.g. "Furniture", "Others" in the
/// source document) — a finding logged against one of these can never
/// get a confident catalogue match and should resolve to
/// `needsReview`.
class DefectCatalogueMainElement {
  const DefectCatalogueMainElement({required this.id, required this.name});

  final String id;
  final String name;
}

class DefectCatalogueComponent {
  const DefectCatalogueComponent({
    required this.id,
    required this.name,
    required this.mainElementId,
  });

  final String id;
  final String name;
  final String mainElementId;
}

/// Queryable wrapper around [kDefectCatalogueEntries] — the rest of
/// the app should go through this rather than searching the raw list
/// directly.
class DefectCatalogue {
  DefectCatalogue._(this._master) {
    _rebuild();
  }

  void _rebuild() {
    final entries = [..._master, ..._custom.values];
    _all = entries;
    _byId = {for (final e in entries) e.id: e};
    _byComponent = _groupBy(entries, (e) => e.componentId);
    _byMainElement = _groupBy(entries, (e) => e.mainElementId);
    final mainElementIds = <String>[];
    final mainElementNames = <String, String>{};
    final componentsById = <String, DefectCatalogueComponent>{};
    for (final e in entries) {
      if (!mainElementNames.containsKey(e.mainElementId)) {
        mainElementIds.add(e.mainElementId);
        mainElementNames[e.mainElementId] = e.mainElementName;
      }
      componentsById.putIfAbsent(
        e.componentId,
        () => DefectCatalogueComponent(
          id: e.componentId,
          name: e.componentName,
          mainElementId: e.mainElementId,
        ),
      );
    }
    // Main elements with zero entries (Furniture, Others) still need to
    // exist for [mainElements] — added separately since they have no
    // rows to derive from.
    for (final id in _kEmptyMainElements.keys) {
      if (!mainElementNames.containsKey(id)) {
        mainElementIds.add(id);
        mainElementNames[id] = _kEmptyMainElements[id]!;
      }
    }
    mainElements = [
      for (final id in mainElementIds)
        DefectCatalogueMainElement(id: id, name: mainElementNames[id]!),
    ];
    components = componentsById.values.toList();
  }

  static final DefectCatalogue instance = DefectCatalogue._(
    kDefectCatalogueEntries,
  );

  final List<DefectCatalogueEntry> _master;
  final Map<String, DefectCatalogueEntry> _custom = {};

  late List<DefectCatalogueEntry> _all;
  late Map<String, DefectCatalogueEntry> _byId;
  late Map<String, List<DefectCatalogueEntry>> _byComponent;
  late Map<String, List<DefectCatalogueEntry>> _byMainElement;

  /// The master catalogue followed by the signed-in company's custom
  /// entries (none unless [replaceCustomEntries] was called).
  List<DefectCatalogueEntry> get entries => _all;

  /// Only the ProDefact master entries — what AI is ever shown.
  List<DefectCatalogueEntry> get masterEntries => _master;

  /// Replaces the whole custom overlay (call on sign-in with that
  /// account's entries, and with `[]` on sign-out / account switch so one
  /// company's entries can never be visible to another). Custom ids never
  /// shadow a master id.
  void replaceCustomEntries(Iterable<DefectCatalogueEntry> custom) {
    _custom
      ..clear()
      ..addEntries([
        for (final e in custom)
          if (e.isCustom && !_master.any((m) => m.id == e.id))
            MapEntry(e.id, e),
      ]);
    _rebuild();
  }

  late List<DefectCatalogueMainElement> mainElements;
  late List<DefectCatalogueComponent> components;

  DefectCatalogueEntry? byId(String id) => _byId[id];

  bool isValidEntryId(String id) => _byId.containsKey(id);

  List<DefectCatalogueEntry> forComponent(String componentId) =>
      _byComponent[componentId] ?? const [];

  List<DefectCatalogueEntry> forMainElement(String mainElementId) =>
      _byMainElement[mainElementId] ?? const [];

  List<DefectCatalogueComponent> componentsForMainElement(
    String mainElementId,
  ) => components.where((c) => c.mainElementId == mainElementId).toList();

  /// Simple case-insensitive text search across defect description,
  /// component, and main element name — backs the inspector's
  /// searchable "Change" picker (see `docs/ai_review.md`).
  List<DefectCatalogueEntry> search(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return entries;
    return entries
        .where(
          (e) =>
              e.defectDescription.toLowerCase().contains(q) ||
              e.componentName.toLowerCase().contains(q) ||
              e.mainElementName.toLowerCase().contains(q),
        )
        .toList();
  }
}

const _kEmptyMainElements = {'furniture': 'Furniture', 'others': 'Others'};

Map<String, List<T>> _groupBy<T>(List<T> items, String Function(T) keyOf) {
  final result = <String, List<T>>{};
  for (final item in items) {
    result.putIfAbsent(keyOf(item), () => []).add(item);
  }
  return result;
}
