// GENERATED FILE — do not edit by hand.
//
// Regenerate with: python3 tool/generate_defect_catalogue.py
// Source of truth: tool/generate_defect_catalogue.py
// (transcribed from "DEFECT_REPORT_LIST.xlsx - DEFECT
// LIST.pdf").

import 'defect_catalogue.dart';

/// All controlled defect catalogue entries — see `DefectCatalogue`
/// (`defect_catalogue.dart`) for the queryable wrapper the rest of the
/// app should use instead of this raw list directly.
const List<DefectCatalogueEntry> kDefectCatalogueEntries = [
  DefectCatalogueEntry(
    id: 'door.door_bell_switch.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_bell_switch',
    componentName: 'Door Bell Switch',
    defectId: 'door.door_bell_switch.01',
    defectDescription: 'Door bell is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_bell_switch.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_bell_switch',
    componentName: 'Door Bell Switch',
    defectId: 'door.door_bell_switch.02',
    defectDescription: 'Door bell switch is damaged/not functioning properly',
    correctiveAction:
        'Replace with a new door bell switch. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_bell_switch.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_bell_switch',
    componentName: 'Door Bell Switch',
    defectId: 'door.door_bell_switch.03',
    defectDescription: 'Door bell switch is loose',
    correctiveAction:
        'Reinstall the door bell switch. Make sure it is firm and tightened.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_bell_switch.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_bell_switch',
    componentName: 'Door Bell Switch',
    defectId: 'door.door_bell_switch.04',
    defectDescription: 'Door bell switch is slanted',
    correctiveAction: 'Readjust the door bell switch alignment. Make sure the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'door.door_bell_switch.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_bell_switch',
    componentName: 'Door Bell Switch',
    defectId: 'door.door_bell_switch.05',
    defectDescription: 'Visible gap between door bell switch and wall',
    correctiveAction:
        'Seal off the gap with sealant/filler. Make sure the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'door.door_closer.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_closer',
    componentName: 'Door Closer',
    defectId: 'door.door_closer.01',
    defectDescription: 'Door closer is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_closer.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_closer',
    componentName: 'Door Closer',
    defectId: 'door.door_closer.02',
    defectDescription: 'Door closer is loose',
    correctiveAction: 'Reinstall the door closer. Make sure it is tightened. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_closer.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_closer',
    componentName: 'Door Closer',
    defectId: 'door.door_closer.03',
    defectDescription: 'Door closer is rusty',
    correctiveAction: 'Replace to a new door closer. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_closer.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_closer',
    componentName: 'Door Closer',
    defectId: 'door.door_closer.04',
    defectDescription: 'Door closer produces creaking sound when opened/closed',
    correctiveAction: 'Reinstall the door closer. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_closer.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_closer',
    componentName: 'Door Closer',
    defectId: 'door.door_closer.05',
    defectDescription: 'Door slams/stops half way when closed. Door closer is not functioning properly',
    correctiveAction:
        'Readjust the door closer alignment. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.01',
    defectDescription: 'Aluminum door frame is damaged/chipped/scratched',
    correctiveAction: 'Sand down the dented area to the bare metal. Apply auto body filler until it is flushed to the surface. Repaint the area with same colour coded door paint.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.02',
    defectDescription: 'Door frame is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.03',
    defectDescription: 'Door frame is not aligned',
    correctiveAction:
        'Readjust the door frame alignment. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.04',
    defectDescription: 'Door frame is rusty',
    correctiveAction: 'Chip off the rust, apply anti-rust coating and repaint with the same colour coded paint',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.05',
    defectDescription:
        'Gap between door frame and wall/floor is not properly sealed off',
    correctiveAction: 'Seal off the gap with silicon/filler. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.06',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.06',
    defectDescription: 'Missing rubber cover on the door frame',
    correctiveAction: 'Install the rubber cover. Make sure it is firm and tightened. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.07',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.07',
    defectDescription: 'Poor paint finishing on the door frame',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.08',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.08',
    defectDescription: 'Visible gap between door frame panels',
    correctiveAction: 'Seal off the gap with silicone/filler. Make sure the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'door.door_frame.09',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_frame',
    componentName: 'Door Frame',
    defectId: 'door.door_frame.09',
    defectDescription: 'Wooden door frame is damaged/chipped/scratched',
    correctiveAction: 'Fill the chipped area with wood filler. Sand down and repaint with the same colour coded paint',
  ),
  DefectCatalogueEntry(
    id: 'door.door_hinge.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_hinge',
    componentName: 'Door Hinge',
    defectId: 'door.door_hinge.01',
    defectDescription: 'Door hinge installation is poor/slanted/gap/loose',
    correctiveAction: 'Reinstall the hinge. Make sure the finishing is good. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_hinge.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_hinge',
    componentName: 'Door Hinge',
    defectId: 'door.door_hinge.02',
    defectDescription: 'Door hinge is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_hinge.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_hinge',
    componentName: 'Door Hinge',
    defectId: 'door.door_hinge.03',
    defectDescription: 'Door hinge is rusty',
    correctiveAction: 'Replace with a new door hinge. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_hinge.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_hinge',
    componentName: 'Door Hinge',
    defectId: 'door.door_hinge.04',
    defectDescription:
        'Door hinge produces a creaking sound when opened/closed',
    correctiveAction: 'Apply lubricant or replace the door hinge if required. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_hinge.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_hinge',
    componentName: 'Door Hinge',
    defectId: 'door.door_hinge.05',
    defectDescription: 'Missing screw on the door hinge',
    correctiveAction: 'Install the missing screw. Make sure it is tightened and firm. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_knob_handle.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_knob_handle',
    componentName: 'Door Knob/Handle',
    defectId: 'door.door_knob_handle.01',
    defectDescription: 'Door handle is damaged/chipped/scratched',
    correctiveAction: 'Replace with a new door handle. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_knob_handle.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_knob_handle',
    componentName: 'Door Knob/Handle',
    defectId: 'door.door_knob_handle.02',
    defectDescription: 'Door handle is loose',
    correctiveAction: 'Reinstall the door handle. Make sure it is tightened. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_knob_handle.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_knob_handle',
    componentName: 'Door Knob/Handle',
    defectId: 'door.door_knob_handle.03',
    defectDescription: 'Door handle is not functioning properly',
    correctiveAction:
        'Replace with a new door knob/handle. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_knob_handle.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_knob_handle',
    componentName: 'Door Knob/Handle',
    defectId: 'door.door_knob_handle.04',
    defectDescription: 'Door handle is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_knob_handle.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_knob_handle',
    componentName: 'Door Knob/Handle',
    defectId: 'door.door_knob_handle.05',
    defectDescription: 'Door knob/handle is rusty',
    correctiveAction:
        'Replace with a new door knob/handle. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_latch.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_latch',
    componentName: 'Door Latch',
    defectId: 'door.door_latch.01',
    defectDescription: 'Door cannot latch properly. Door latch does not align to the door strike plate',
    correctiveAction:
        'Readjust the door strike plate alignment. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_latch.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_latch',
    componentName: 'Door Latch',
    defectId: 'door.door_latch.02',
    defectDescription: 'Door latch is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_latch.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_latch',
    componentName: 'Door Latch',
    defectId: 'door.door_latch.03',
    defectDescription:
        'Door latch is stuck to the door strike plate when closed',
    correctiveAction:
        'Readjust the door strike plate alignment. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_latch.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_latch',
    componentName: 'Door Latch',
    defectId: 'door.door_latch.04',
    defectDescription:
        'Door strike plate does not flush to the door leaf. Poor installation',
    correctiveAction: 'Readjust the door strike plate alignment. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_leaf.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_leaf',
    componentName: 'Door Leaf',
    defectId: 'door.door_leaf.01',
    defectDescription: 'Door in contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_leaf.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_leaf',
    componentName: 'Door Leaf',
    defectId: 'door.door_leaf.02',
    defectDescription: 'Door leaf clashes with others elements when closed',
    correctiveAction: 'Readjust the door leaf alignment. Make sure it can be opened/closed smoothly.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_leaf.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_leaf',
    componentName: 'Door Leaf',
    defectId: 'door.door_leaf.03',
    defectDescription: 'Door leaf does not flush with door frame when closed',
    correctiveAction: 'Readjust the door leaf alignment. Make sure it flushes with the door frame when closed.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_leaf.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_leaf',
    componentName: 'Door Leaf',
    defectId: 'door.door_leaf.04',
    defectDescription: 'Door leaf is cracked/damaged/chipped',
    correctiveAction: 'Fill the chipped area with wood filler. Sand down and repaint with same colour coded paint',
  ),
  DefectCatalogueEntry(
    id: 'door.door_leaf.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_leaf',
    componentName: 'Door Leaf',
    defectId: 'door.door_leaf.05',
    defectDescription: 'Door leaf is not aligned/rattles when closed',
    correctiveAction: 'Readjust the door leaf alignment. Make sure it is flushed to the door frame when closed. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_leaf.06',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_leaf',
    componentName: 'Door Leaf',
    defectId: 'door.door_leaf.06',
    defectDescription: 'Insufficient rubber seal length',
    correctiveAction: 'Install the door seal with sufficient length. Make sure it is firm and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_leaf.07',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_leaf',
    componentName: 'Door Leaf',
    defectId: 'door.door_leaf.07',
    defectDescription: 'Poor paint finishing on the door leaf. Top/bottom part of the door is not painted',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_lockset.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_lockset',
    componentName: 'Door Lockset',
    defectId: 'door.door_lockset.01',
    defectDescription: 'Door lockset screw is rusty',
    correctiveAction: 'Replace with the same screw type. Make sure it is firm and tightened. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_lockset.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_lockset',
    componentName: 'Door Lockset',
    defectId: 'door.door_lockset.02',
    defectDescription:
        'Keys provided do not match with the door lockset/unable to use',
    correctiveAction: 'Provide the keys that match with the door lockset.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_stopper.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_stopper',
    componentName: 'Door Stopper',
    defectId: 'door.door_stopper.01',
    defectDescription: 'Door stopper is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_stopper.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_stopper',
    componentName: 'Door Stopper',
    defectId: 'door.door_stopper.02',
    defectDescription: 'Door stopper is loose',
    correctiveAction:
        'Reinstall the door stopper. Make sure it is firm and tightened.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_stopper.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_stopper',
    componentName: 'Door Stopper',
    defectId: 'door.door_stopper.03',
    defectDescription: 'Door stopper is not functioning properly',
    correctiveAction: 'Replace with a new door stopper. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_stopper.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_stopper',
    componentName: 'Door Stopper',
    defectId: 'door.door_stopper.04',
    defectDescription: 'Door stopper is rusty',
    correctiveAction:
        'Replace with a new door stopper. Make sure it is firm and tightened.',
  ),
  DefectCatalogueEntry(
    id: 'door.door_stopper.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_stopper',
    componentName: 'Door Stopper',
    defectId: 'door.door_stopper.05',
    defectDescription: 'Missing door stopper',
    correctiveAction: 'Install the door stopper. Make sure it is firm and tightened. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.door_stopper.06',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.door_stopper',
    componentName: 'Door Stopper',
    defectId: 'door.door_stopper.06',
    defectDescription: 'Poor installation of door stopper',
    correctiveAction:
        'Reinstall the door stopper. Make sure it is firm and tightened.',
  ),
  DefectCatalogueEntry(
    id: 'door.grill_door.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.grill_door',
    componentName: 'Grill Door',
    defectId: 'door.grill_door.01',
    defectDescription: 'Grill door is dented/chipped/scratched',
    correctiveAction: 'Sand down the dented area to the bare metal. Apply auto body filler until it is flushed to the surface. Repaint the area with same colour coded door paint.',
  ),
  DefectCatalogueEntry(
    id: 'door.grill_door.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.grill_door',
    componentName: 'Grill Door',
    defectId: 'door.grill_door.02',
    defectDescription: 'Door grill is not aligned',
    correctiveAction: 'Reinstall the door grill. Make sure it is aligned and test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'door.grill_door.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.grill_door',
    componentName: 'Grill Door',
    defectId: 'door.grill_door.03',
    defectDescription: 'Grill is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.grill_door.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.grill_door',
    componentName: 'Grill Door',
    defectId: 'door.grill_door.04',
    defectDescription: 'Latch hole is missing/misaligned',
    correctiveAction: 'Provide the latch hole. Test the functionality.',
  ),
  DefectCatalogueEntry(
    id: 'door.grill_door.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.grill_door',
    componentName: 'Grill Door',
    defectId: 'door.grill_door.05',
    defectDescription: 'Missing lock pin on the grill door hinge',
    correctiveAction: 'Provide and install the lock pin. Make sure it tightened. Test for grill door functionality.',
  ),
  DefectCatalogueEntry(
    id: 'door.grill_door.06',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.grill_door',
    componentName: 'Grill Door',
    defectId: 'door.grill_door.06',
    defectDescription:
        'Poor paint finishing on the grill door/paint peeled off',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.01',
    defectDescription:
        'Gap between sliding door frame and wall is not properly sealed off',
    correctiveAction:
        'Seal off the gap with sealant/filler. Make sure the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.02',
    defectDescription: 'Missing rubber seal/rubber seal is peeled off',
    correctiveAction:
        'Install the rubber seal. Make sure the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.03',
    defectDescription: 'Missing screw on the sliding door frame',
    correctiveAction: 'Install with the same screw type. Make sure it is firm and tightened. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.04',
    defectDescription: 'Poor paint finishing on the sliding door frame',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.05',
    defectDescription: 'Sliding door frame is damaged/chipped/scratched',
    correctiveAction: 'Sand down the dented area to the bare metal. Apply auto body filler until it is flushed to the surface. Repaint the area with same colour coded door paint.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.06',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.06',
    defectDescription: 'Sliding door frame is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.07',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.07',
    defectDescription: 'Sliding door frame is not aligned',
    correctiveAction:
        'Readjust the sliding door frame alignment. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_frame.08',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_frame',
    componentName: 'Sliding Door Frame',
    defectId: 'door.sliding_door_frame.08',
    defectDescription: 'Sliding door frame is rusty',
    correctiveAction: 'Chip off the rust, apply anti-rust coating and repaint with the same colour coded paint',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_glass.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_glass',
    componentName: 'Sliding Door Glass',
    defectId: 'door.sliding_door_glass.01',
    defectDescription: 'Sliding door glass is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_glass.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_glass',
    componentName: 'Sliding Door Glass',
    defectId: 'door.sliding_door_glass.02',
    defectDescription: 'Sliding door glass is damaged/chipped/scratched',
    correctiveAction:
        'Replace with a new glass panel. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.01',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.01',
    defectDescription:
        'Gap between sliding door panels is not properly sealed off',
    correctiveAction:
        'Seal off the gap with sealant/filler. Make sure the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.02',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.02',
    defectDescription: 'Missing rubber cover on the door frame',
    correctiveAction: 'Install the rubber cover. Make sure it is firm and tightened. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.03',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.03',
    defectDescription: 'Missing rubber seal/rubber seal is peeled off',
    correctiveAction:
        'Install the rubber seal. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.04',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.04',
    defectDescription: 'Poor paint finishing on the sliding door panel',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.05',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.05',
    defectDescription: 'Sliding door is damaged/chipped/scratched',
    correctiveAction: 'Sand down the dented area to the bare metal. Apply auto body filler until it is flushed to the surface. Repaint the area with same colour coded door paint.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.06',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.06',
    defectDescription: 'Sliding door panel is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.07',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.07',
    defectDescription: 'Sliding door panel is not aligned',
    correctiveAction:
        'Readjust the sliding door panel alignment. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.08',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.08',
    defectDescription: 'Sliding door panel is not functioning properly',
    correctiveAction:
        'Readjust the sliding door panel alignment. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.09',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.09',
    defectDescription: 'Sliding door panel is rusty',
    correctiveAction: 'Chip off the rust, apply anti-rust coating and repaint with the same colour coded paint',
  ),
  DefectCatalogueEntry(
    id: 'door.sliding_door_panel.10',
    mainElementId: 'door',
    mainElementName: 'Door',
    componentId: 'door.sliding_door_panel',
    componentName: 'Sliding Door Panel',
    defectId: 'door.sliding_door_panel.10',
    defectDescription:
        'Sliding door panel produces a creaking sound when opened/and closed',
    correctiveAction: 'Apply lubricant or reinstall the door panel if required. Test the functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_awning.01',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_awning',
    componentName: 'Window Awning',
    defectId: 'window.window_awning.01',
    defectDescription: 'Poor painting finishing on the window awning',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_awning.02',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_awning',
    componentName: 'Window Awning',
    defectId: 'window.window_awning.02',
    defectDescription: 'Window awning is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_awning.03',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_awning',
    componentName: 'Window Awning',
    defectId: 'window.window_awning.03',
    defectDescription: 'Window awning is damaged/chipped/scratched',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_awning.04',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_awning',
    componentName: 'Window Awning',
    defectId: 'window.window_awning.04',
    defectDescription: 'Window awning is not aligned/slanted',
    correctiveAction: 'Readjust the window awning alignment. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.01',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.01',
    defectDescription:
        'Gap between window frame and wall is not properly sealed off',
    correctiveAction:
        'Seal off the gap with sealant/filler. Make sure the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.02',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.02',
    defectDescription: 'Insufficient rubber seal on the window frame',
    correctiveAction: 'Replace with a new rubber seal with sufficient length. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.03',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.03',
    defectDescription: 'Missing rubber seal/rubber seal is peeled off',
    correctiveAction:
        'Install the new rubber seal. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.04',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.04',
    defectDescription: 'Missing screw on the window frame',
    correctiveAction: 'Install with the same screw type. Make sure it is tightened and firm. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.05',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.05',
    defectDescription: 'Poor paint finishing on the window frame',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.06',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.06',
    defectDescription: 'Poor window frame installation',
    correctiveAction:
        'Reinstall the window frame. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.07',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.07',
    defectDescription: 'Visible gap between window frame',
    correctiveAction: 'Seal off the gap with silicone/filler. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.08',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.08',
    defectDescription: 'Window frame are contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.09',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.09',
    defectDescription: 'Window frame is damaged/chipped/scratched',
    correctiveAction: 'Sand down the dented area to the bare metal. Apply auto body filler until it is flushed to the surface. Repaint the area with same colour coded window paint.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.10',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.10',
    defectDescription: 'Window frame is not aligned/slanted',
    correctiveAction:
        'Readjust the window frame alignment. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_frame.11',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_frame',
    componentName: 'Window Frame',
    defectId: 'window.window_frame.11',
    defectDescription: 'Window frame is rusty',
    correctiveAction: 'Chip off the rust, apply anti-rust coating and repaint with the same colour coded paint.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_glass.01',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_glass',
    componentName: 'Window Glass',
    defectId: 'window.window_glass.01',
    defectDescription: 'Window glass are contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_glass.02',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_glass',
    componentName: 'Window Glass',
    defectId: 'window.window_glass.02',
    defectDescription: 'Window glass is damaged/chipped/scratched',
    correctiveAction:
        'Replace with a new glass panel. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_handle.01',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_handle',
    componentName: 'Window Handle',
    defectId: 'window.window_handle.01',
    defectDescription: 'Missing screw on the window handle',
    correctiveAction: 'Install the missing screw. Make sure it is tightened and firm. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_handle.02',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_handle',
    componentName: 'Window Handle',
    defectId: 'window.window_handle.02',
    defectDescription: 'Rusty screw on window handle',
    correctiveAction:
        'Replace with the same screw type. Make sure it is firm and tightened',
  ),
  DefectCatalogueEntry(
    id: 'window.window_handle.03',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_handle',
    componentName: 'Window Handle',
    defectId: 'window.window_handle.03',
    defectDescription: 'Window handle is loose',
    correctiveAction: 'Reinstall with the new window handle. Make sure it is tightened. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_handle.04',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_handle',
    componentName: 'Window Handle',
    defectId: 'window.window_handle.04',
    defectDescription: 'Window handle is not functioning properly',
    correctiveAction:
        'Replace with a new window handle. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_handle.05',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_handle',
    componentName: 'Window Handle',
    defectId: 'window.window_handle.05',
    defectDescription: 'Window handle are contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_handle.06',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_handle',
    componentName: 'Window Handle',
    defectId: 'window.window_handle.06',
    defectDescription: 'Window handle is damaged/chipped/scratched',
    correctiveAction:
        'Replace with a new window handle. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_hinge.01',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_hinge',
    componentName: 'Window Hinge',
    defectId: 'window.window_hinge.01',
    defectDescription: 'Missing screw on the window hinge',
    correctiveAction: 'Install the missing screw. Make sure it is tightened and firm. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_hinge.02',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_hinge',
    componentName: 'Window Hinge',
    defectId: 'window.window_hinge.02',
    defectDescription: 'Window hinge installation is poor/loose',
    correctiveAction: 'Reinstall the hinge. Make sure the finishing is good. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_hinge.03',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_hinge',
    componentName: 'Window Hinge',
    defectId: 'window.window_hinge.03',
    defectDescription: 'Window hinge is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_hinge.04',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_hinge',
    componentName: 'Window Hinge',
    defectId: 'window.window_hinge.04',
    defectDescription: 'Window hinge is rusty',
    correctiveAction:
        'Replace with a new window hinge. Test for window functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_hinge.05',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_hinge',
    componentName: 'Window Hinge',
    defectId: 'window.window_hinge.05',
    defectDescription:
        'Window hinge is stuck. Window cannot be closed properly.',
    correctiveAction: 'Reinstall the hinge. Make sure the finishing is good. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_hinge.06',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_hinge',
    componentName: 'Window Hinge',
    defectId: 'window.window_hinge.06',
    defectDescription:
        'Window hinge produces a creaking sound when opened/closed.',
    correctiveAction: 'Apply lubricant or replace the window hinge if required. Tests for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.01',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.01',
    defectDescription: 'Insufficient rubber seal on the window leaf',
    correctiveAction: 'Replace with a new rubber seal with sufficient length. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.02',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.02',
    defectDescription: 'Missing rubber seal/rubber seal is peeled off',
    correctiveAction:
        'Install the rubber seal. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.03',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.03',
    defectDescription: 'Poor paint finishing on the window leaf',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.04',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.04',
    defectDescription: 'Window cannot be closed properly',
    correctiveAction: 'Readjust the window alignment. Make sure it is flushed to the frame when closed. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.05',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.05',
    defectDescription: 'Window leaf clashes with wall when opened/closed',
    correctiveAction:
        'Readjust the window leaf alignment. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.06',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.06',
    defectDescription: 'Window leaf is contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.07',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.07',
    defectDescription: 'Window leaf is damaged/chipped/scratched',
    correctiveAction: 'Sand down the affected area to the bare metal. Apply auto body filler until it is flushed to the surface. Repaint the area with same colour coded window paint.',
  ),
  DefectCatalogueEntry(
    id: 'window.window_leaf.08',
    mainElementId: 'window',
    mainElementName: 'Window',
    componentId: 'window.window_leaf',
    componentName: 'Window Leaf',
    defectId: 'window.window_leaf.08',
    defectDescription: 'Window leaf is not aligned with the window frame. Inconsistent gap when close.',
    correctiveAction: 'Readjust the window alignment. Make sure it is flushed to the frame when closed. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.01',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.01',
    defectDescription: 'Gap is not properly sealed off',
    correctiveAction: 'Seal off the gap with silicone/filler. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.02',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.02',
    defectDescription: 'Hairline crack on the wall',
    correctiveAction: 'Cut along the hairline crack, install fibre/wire mesh, fill the area with skim filler, sand down the surface and repaint with same colour coded paint. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.03',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.03',
    defectDescription: 'Poor skim/paint finishing',
    correctiveAction: 'Apply skim coat and sand down the affected area.',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.04',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.04',
    defectDescription: 'Wall is bulging',
    correctiveAction: 'Chip off the affected area, apply Portland cement, fill the area with skim filler, sand down the surface and repaint with same colour coded paint. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.05',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.05',
    defectDescription: 'Wall is chipped',
    correctiveAction: 'Fill the affected area with skim filler, sand down and repaint with same colour coded paint. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.06',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.06',
    defectDescription: 'Wall in contaminated with stain',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.07',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.07',
    defectDescription: 'Wall is uneven/not straight',
    correctiveAction: 'Chip off the affected area, apply Portland cement, fill the area with skim filler, sand down the surface and repaint with same colour coded paint. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.08',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.08',
    defectDescription: 'Wall squareness exceeds tolerance',
    correctiveAction: 'Readjust the wall alignment. Make sure the wall alignment is within the acceptable tolerance <4mm',
  ),
  DefectCatalogueEntry(
    id: 'wall.concrete_wall.09',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.concrete_wall',
    componentName: 'Concrete Wall',
    defectId: 'wall.concrete_wall.09',
    defectDescription: 'Watermark stain spotted on the wall',
    correctiveAction: 'Further investigation must be made to check on the source of leakage. This problem must be rectified according to the approved method statement from the consultant/SO',
  ),
  DefectCatalogueEntry(
    id: 'wall.wall_tile.01',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.wall_tile',
    componentName: 'Wall Tile',
    defectId: 'wall.wall_tile.01',
    defectDescription: 'Inconsistent grout colour tone',
    correctiveAction: 'Grout the gap between the tiles with the same tile gap filler tone. Make sure the gap is fully sealed',
  ),
  DefectCatalogueEntry(
    id: 'wall.wall_tile.02',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.wall_tile',
    componentName: 'Wall Tile',
    defectId: 'wall.wall_tile.02',
    defectDescription: 'Tile gap is not properly sealed off. Poor finishing',
    correctiveAction: 'Grout the gap between the tiles with tile gap filler. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.wall_tile.03',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.wall_tile',
    componentName: 'Wall Tile',
    defectId: 'wall.wall_tile.03',
    defectDescription:
        'Wall tile/tile grout is contaminated with stain/scratched',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'wall.wall_tile.04',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.wall_tile',
    componentName: 'Wall Tile',
    defectId: 'wall.wall_tile.04',
    defectDescription: 'Wall tile inconsistent colour tone/Wall tile is damaged/chipped/hollow/uneven/not straight',
    correctiveAction: 'Replace with a new tile with the same colour coded. Ensure the tile alignment is consistent and tile adhesive is fully spread. Test for tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'wall.wall_tile.05',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.wall_tile',
    componentName: 'Wall Tile',
    defectId: 'wall.wall_tile.05',
    defectDescription: 'Wall tile is not aligned/lippage',
    correctiveAction: 'Readjust the tile alignment. Make sure it is consistent and the finishing is good',
  ),
  DefectCatalogueEntry(
    id: 'wall.wall_tile.06',
    mainElementId: 'wall',
    mainElementName: 'Wall',
    componentId: 'wall.wall_tile',
    componentName: 'Wall Tile',
    defectId: 'wall.wall_tile.06',
    defectDescription: 'Wall tile opening is not sealed off',
    correctiveAction: 'Seal off the gap with sealant/filler. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.01',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.01',
    defectDescription: 'Timber floor are contaminated with stain.',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.02',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.02',
    defectDescription: 'Floor board has different colour tone',
    correctiveAction: 'Replace with the same colour coded floor board. Make sure the surface is even, the alignment is consistent and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.03',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.03',
    defectDescription: 'Floor board is damaged/chipped/scratched',
    correctiveAction: 'Replace with the same colour coded floor board. Make sure the surface is even, the alignment is consistent and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.04',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.04',
    defectDescription: 'Floor board is uneven/lippage',
    correctiveAction: 'Reinstall the floor panel. Make sure the surface is even, the alignment is consistent and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.05',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.05',
    defectDescription: 'Floor board is wobbly and not firm',
    correctiveAction: 'Reinstall the floor panel. Make sure the surface is even, the alignment is consistent and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.06',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.06',
    defectDescription:
        'Floor coating finishing is poor/faded/not properly done',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/S.O.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.07',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.07',
    defectDescription:
        'Gap between floor board and door frame is not properly sealed off',
    correctiveAction: 'Grout the gap with gap filler. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.08',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.08',
    defectDescription: 'Gap between floor board is not sealed off',
    correctiveAction: 'Grout the gap between the floor board with sealant/filler. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.09',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.09',
    defectDescription: 'Gap between floor skirting and wall is not sealed off',
    correctiveAction: 'Grout the gap with gap filler/sealant. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.10',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.10',
    defectDescription: 'Inconsistent gap between floor board',
    correctiveAction:
        'Readjust the floor board alignment. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.timber_floor.11',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.timber_floor',
    componentName: 'Timber Floor',
    defectId: 'floor.timber_floor.11',
    defectDescription:
        'Visible gap between floor skirt and floor board when load is applied',
    correctiveAction: 'Grout the gap with gap filler/sealant. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.01',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.01',
    defectDescription: 'Wood skirting is contaminated with stains.',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.02',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.02',
    defectDescription:
        'Gap between skirting and wall is not properly sealed off',
    correctiveAction: 'Grout the gap between the wall with gap filler. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.03',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.03',
    defectDescription: 'Poor finishing on the wood skirting',
    correctiveAction: 'Reinstall the wood skirting. Make sure it is firm and the finishing is good. Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.04',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.04',
    defectDescription:
        'Wood skirting gap is not properly sealed off. Poor finishing',
    correctiveAction: 'Grout the gap with gap filler. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.05',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.05',
    defectDescription: 'Wood skirting has inconsistent colour tone',
    correctiveAction: 'Sand down the affected area. Repaint with the same colour coded paint. Make sure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.06',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.06',
    defectDescription: 'Wood skirting is damaged/chipped/cracked',
    correctiveAction: 'Replace with a new skirting with the same colour coded. Ensure the tile alignment is consistent and adhesive is fully spread.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.07',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.07',
    defectDescription: 'Wood skirting lippage exceeds tolerance',
    correctiveAction: 'Readjust the skirting alignment. Make sure the surface is even and the tile adhesive is fully spread.',
  ),
  DefectCatalogueEntry(
    id: 'floor.wood_skirting.08',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.wood_skirting',
    componentName: 'Wood Skirting',
    defectId: 'floor.wood_skirting.08',
    defectDescription: 'Wood skirting paint peeled off',
    correctiveAction: 'Repaint the affected area with the same colour coded paint. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.01',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.01',
    defectDescription: 'Floor tile are contaminated with stain/scratched.',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.02',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.02',
    defectDescription: 'Floor tile inconsistent colour tone.',
    correctiveAction: 'Replace with a new tile with the same colour tone. Ensure the tile alignment is consistent and tile adhesive is fully spread. Test the tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.03',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.03',
    defectDescription: 'Floor tile is chipped/damaged.',
    correctiveAction: 'Replace with a new tile with the same colour tone. Ensure the tile alignment is consistent and tile adhesive is fully spread. Test the tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.04',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.04',
    defectDescription: 'Floor tile is faded',
    correctiveAction: 'Replace with a new tile with the same colour tone. Ensure the tile alignment is consistent and tile adhesive is fully spread. Test the tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.05',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.05',
    defectDescription: 'Floor tile is hollow.',
    correctiveAction: 'Replace with a new tile with the same colour tone. Ensure the tile alignment is consistent and tile adhesive is fully spread. Test the tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.06',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.06',
    defectDescription: 'Floor tile is uneven/not straight.',
    correctiveAction: 'Replace with a new tile with the same colour tone. Ensure the tile alignment is consistent and tile adhesive is fully spread. Test the tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.07',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.07',
    defectDescription: 'Floor tile lippage exceeds tolerance',
    correctiveAction: 'Readjust the tile alignment. Make sure the surface is even and tile adhesive is fully spread. Test for tile hollowness and evenness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.08',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.08',
    defectDescription:
        'Gap between floor tile and door frame is not properly sealed off.',
    correctiveAction: 'Grout the gap with gap filler. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.09',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.09',
    defectDescription: 'Inconsistent grout colour tone.',
    correctiveAction: 'Grout the gap between the tiles with the same tile gap filler tone. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.10',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.10',
    defectDescription: 'Tile edge is sharp',
    correctiveAction:
        'Chamfer the tile edge. Make sure the finishing is smooth and good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.11',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.11',
    defectDescription: 'Tile gap is not properly sealed off. Poor finishing',
    correctiveAction: 'Grout the gap between the tiles with tile gap filler. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.floor_tiles.12',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.floor_tiles',
    componentName: 'Floor Tiles',
    defectId: 'floor.floor_tiles.12',
    defectDescription: 'Water remains stagnant on one side of the floor.',
    correctiveAction: 'Readjust the floor tiles gradient. Make sure the finishing is good and the gradient is directed towards the floor trap. Test with spirit level.',
  ),
  DefectCatalogueEntry(
    id: 'floor.tiles_skirting.01',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.tiles_skirting',
    componentName: 'Tiles Skirting',
    defectId: 'floor.tiles_skirting.01',
    defectDescription: 'Tiles skirting is contaminated with stain.',
    correctiveAction: 'Remove the stain and clean the affected area. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.tiles_skirting.02',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.tiles_skirting',
    componentName: 'Tiles Skirting',
    defectId: 'floor.tiles_skirting.02',
    defectDescription: 'Inconsistent grout colour tone',
    correctiveAction: 'Grout the between the tiles with the same tile gap filler tone. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.tiles_skirting.03',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.tiles_skirting',
    componentName: 'Tiles Skirting',
    defectId: 'floor.tiles_skirting.03',
    defectDescription: 'Tile gap is not properly sealed off. Poor finishing',
    correctiveAction: 'Grout the between the tiles with the tile gap filler tone. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'floor.tiles_skirting.04',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.tiles_skirting',
    componentName: 'Tiles Skirting',
    defectId: 'floor.tiles_skirting.04',
    defectDescription: 'Tile skirting inconsistent colour tone',
    correctiveAction: 'Replace with a new tile with the same colour code. Ensure the tile alignment is consistent and the tile adhesive is fully spread. Test for tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.tiles_skirting.05',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.tiles_skirting',
    componentName: 'Tiles Skirting',
    defectId: 'floor.tiles_skirting.05',
    defectDescription: 'Tiles skirting is damaged/chipped',
    correctiveAction: 'Replace with a new tile with the same colour code. Ensure the tile alignment is consistent and the tile adhesive is fully spread. Test for tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.tiles_skirting.06',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.tiles_skirting',
    componentName: 'Tiles Skirting',
    defectId: 'floor.tiles_skirting.06',
    defectDescription: 'Tile skirting is hollow',
    correctiveAction: 'Replace with a new tile with the same colour code. Ensure the tile alignment is consistent and the tile adhesive is fully spread. Test for tile hollowness.',
  ),
  DefectCatalogueEntry(
    id: 'floor.tiles_skirting.07',
    mainElementId: 'floor',
    mainElementName: 'Floor',
    componentId: 'floor.tiles_skirting',
    componentName: 'Tiles Skirting',
    defectId: 'floor.tiles_skirting.07',
    defectDescription: 'Tile skirting lippage exceeds tolerance',
    correctiveAction: 'Readjust the tile alignment. Make sure the surface is even and tile adhesive is fully spread. Test for tile hollowness and evenness.',
  ),
  DefectCatalogueEntry(
    id: 'roof.roof_tiles.01',
    mainElementId: 'roof',
    mainElementName: 'Roof',
    componentId: 'roof.roof_tiles',
    componentName: 'Roof Tiles',
    defectId: 'roof.roof_tiles.01',
    defectDescription: 'Roof tiles are chipped/damaged',
    correctiveAction: 'Replace with a new roof tile. Make sure it is aligned and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'roof.roof_tiles.02',
    mainElementId: 'roof',
    mainElementName: 'Roof',
    componentId: 'roof.roof_tiles',
    componentName: 'Roof Tiles',
    defectId: 'roof.roof_tiles.02',
    defectDescription: 'Roof tile is not aligned/not installed properly',
    correctiveAction: 'Reinstall the roof tile. Make sure it is aligned and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.01',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.01',
    defectDescription: 'Ceiling bracket is rusty',
    correctiveAction: 'Replace with a new ceiling bracket. Make sure it is firm and tightened.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.02',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.02',
    defectDescription: 'Ceiling is chipped',
    correctiveAction: 'Filled the affected area with a skim filler, sand down and repaint with same colour coded paint. Ensure surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.03',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.03',
    defectDescription: 'Ceiling is uneven/not straight',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.04',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.04',
    defectDescription: 'Construction debris left above the ceiling',
    correctiveAction: 'Remove the debris. Make sure the area is clean.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.05',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.05',
    defectDescription:
        'Gap between ceiling and wall is not properly sealed off',
    correctiveAction: 'Seal off the gap with silicon/filler. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.06',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.06',
    defectDescription: 'Hairline crack on the ceiling',
    correctiveAction: 'Cut along the hairline crack, install fibre/wire mesh, fill the area with skim filler, sand down the surface and repaint with same colour coded paint.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.07',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.07',
    defectDescription:
        'Missing water drip grooveline/Poor water drip grooveline finishing',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.08',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.08',
    defectDescription: 'Poor skim/paint finishing',
    correctiveAction: 'Apply skim coat and sand down the affected area. Repaint with the same colour coded paint and ensure the surface is smooth and even.',
  ),
  DefectCatalogueEntry(
    id: 'ceiling.ceiling.09',
    mainElementId: 'ceiling',
    mainElementName: 'Ceiling',
    componentId: 'ceiling.ceiling',
    componentName: 'Ceiling',
    defectId: 'ceiling.ceiling.09',
    defectDescription: 'Watermark stain spotted on the ceiling',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.bottle_trap.01',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.bottle_trap',
    componentName: 'Bottle Trap',
    defectId: 'plumbing.bottle_trap.01',
    defectDescription: 'Bottle trap is clogged/slow draining',
    correctiveAction: 'Remove any debris and clear the bottle trap. Test for water flow. Replace if required.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.bottle_trap.02',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.bottle_trap',
    componentName: 'Bottle Trap',
    defectId: 'plumbing.bottle_trap.02',
    defectDescription: 'Bottle trap is damaged',
    correctiveAction: 'Replace with a new bottle trap. Make sure the height is right. Test for water flow and water leakage.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.bottle_trap.03',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.bottle_trap',
    componentName: 'Bottle Trap',
    defectId: 'plumbing.bottle_trap.03',
    defectDescription: 'Bottle trap is leaking',
    correctiveAction: 'Check the source of leakage. Apply Teflon tape around the pipe thread. Replace if required. Test for water leakage.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.bottle_trap.04',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.bottle_trap',
    componentName: 'Bottle Trap',
    defectId: 'plumbing.bottle_trap.04',
    defectDescription: 'Bottle trap is loose',
    correctiveAction: 'Reinstall the bottle trap. Make sure it is firm and tighten. Apply Teflon tape around the pipe thread and test for water leakage.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.discharge_pipe.01',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.discharge_pipe',
    componentName: 'Discharge Pipe',
    defectId: 'plumbing.discharge_pipe.01',
    defectDescription: 'Discharge pipe is clogged/slow draining',
    correctiveAction:
        'Remove any debris and clear the discharge pipe. Test for water flow.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.discharge_pipe.02',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.discharge_pipe',
    componentName: 'Discharge Pipe',
    defectId: 'plumbing.discharge_pipe.02',
    defectDescription: 'Discharge pipe is damage',
    correctiveAction: 'Replace with a new discharge pipe. Make sure the gradient is right. Test for water flow and water leakage.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.discharge_pipe.03',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.discharge_pipe',
    componentName: 'Discharge Pipe',
    defectId: 'plumbing.discharge_pipe.03',
    defectDescription: 'Discharge pipe is leaking',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'plumbing.discharge_pipe.04',
    mainElementId: 'plumbing',
    mainElementName: 'Plumbing',
    componentId: 'plumbing.discharge_pipe',
    componentName: 'Discharge Pipe',
    defectId: 'plumbing.discharge_pipe.04',
    defectDescription: 'Discharge pipe is slanted/reversed gradient',
    correctiveAction: 'Reinstall the discharge pipe. Make sure the gradient towards the right direction. Test with spirit level and water flow.',
  ),
  DefectCatalogueEntry(
    id: 'electrical_fitting.distribution_board.01',
    mainElementId: 'electrical_fitting',
    mainElementName: 'Electrical Fitting',
    componentId: 'electrical_fitting.distribution_board',
    componentName: 'Distribution Board',
    defectId: 'electrical_fitting.distribution_board.01',
    defectDescription: 'DB cover is damaged',
    correctiveAction:
        'Replace with a new DB cover. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'electrical_fitting.distribution_board.02',
    mainElementId: 'electrical_fitting',
    mainElementName: 'Electrical Fitting',
    componentId: 'electrical_fitting.distribution_board',
    componentName: 'Distribution Board',
    defectId: 'electrical_fitting.distribution_board.02',
    defectDescription: 'DB is not properly installed',
    correctiveAction: 'Reinstall the DB. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'electrical_fitting.distribution_board.03',
    mainElementId: 'electrical_fitting',
    mainElementName: 'Electrical Fitting',
    componentId: 'electrical_fitting.distribution_board',
    componentName: 'Distribution Board',
    defectId: 'electrical_fitting.distribution_board.03',
    defectDescription:
        'Earthing for metal DB cover leakage protection is not provided',
    correctiveAction: 'Install the earthing link for safety purpose.',
  ),
  DefectCatalogueEntry(
    id: 'electrical_fitting.distribution_board.04',
    mainElementId: 'electrical_fitting',
    mainElementName: 'Electrical Fitting',
    componentId: 'electrical_fitting.distribution_board',
    componentName: 'Distribution Board',
    defectId: 'electrical_fitting.distribution_board.04',
    defectDescription: 'Gap between DB and wall is not properly sealed off',
    correctiveAction: 'Seal off the gap with sealant/filler. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'electrical_fitting.distribution_board.05',
    mainElementId: 'electrical_fitting',
    mainElementName: 'Electrical Fitting',
    componentId: 'electrical_fitting.distribution_board',
    componentName: 'Distribution Board',
    defectId: 'electrical_fitting.distribution_board.05',
    defectDescription: 'Missing blank plate cover on the unused slot',
    correctiveAction: 'Install the blank plate cover on the unused slot. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'electrical_fitting.distribution_board.06',
    mainElementId: 'electrical_fitting',
    mainElementName: 'Electrical Fitting',
    componentId: 'electrical_fitting.distribution_board',
    componentName: 'Distribution Board',
    defectId: 'electrical_fitting.distribution_board.06',
    defectDescription: 'Missing screw on the DB cover',
    correctiveAction: 'Install the missing screw. Make sure it is tightened and firm. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'electrical_fitting.distribution_board.07',
    mainElementId: 'electrical_fitting',
    mainElementName: 'Electrical Fitting',
    componentId: 'electrical_fitting.distribution_board',
    componentName: 'Distribution Board',
    defectId: 'electrical_fitting.distribution_board.07',
    defectDescription: 'Single line diagram and MCB label are not provided',
    correctiveAction: 'Provide the Single Line Diagram and MCB label for owner\'s future maintenance purpose.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.01',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.01',
    defectDescription: 'Missing shower head',
    correctiveAction: null,
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.02',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.02',
    defectDescription: 'No hot water supply',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.03',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.03',
    defectDescription: 'Shower head is chipped/damaged/dented',
    correctiveAction:
        'Reinstall the shower head. Test for functionality and leakage',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.04',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.04',
    defectDescription: 'Shower head is leaking',
    correctiveAction: null,
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.05',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.05',
    defectDescription: 'Shower head is loose',
    correctiveAction: 'Reinstall the shower head. Make sure it is tightened and firm. Test for functionality and leakage',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.06',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.06',
    defectDescription: 'Shower head is not functioning properly',
    correctiveAction: 'Replace with a new shower head. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.07',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.07',
    defectDescription: 'Shower head is rusty',
    correctiveAction: 'Replace with a new shower head. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.08',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.08',
    defectDescription: 'Shower head is slanted',
    correctiveAction:
        'Readjust the shower head alignment. Make sure the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.shower_head.09',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.shower_head',
    componentName: 'Shower Head',
    defectId: 'sanitary_fitting.shower_head.09',
    defectDescription: 'Shower head water pressure is low',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.water_tap.01',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.water_tap',
    componentName: 'Water Tap',
    defectId: 'sanitary_fitting.water_tap.01',
    defectDescription: 'No hot water supply',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.water_tap.02',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.water_tap',
    componentName: 'Water Tap',
    defectId: 'sanitary_fitting.water_tap.02',
    defectDescription: 'Water tap is damaged',
    correctiveAction: 'Replace with a new water tap. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.water_tap.03',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.water_tap',
    componentName: 'Water Tap',
    defectId: 'sanitary_fitting.water_tap.03',
    defectDescription: 'Water tap is leaking/dripping',
    correctiveAction: 'Check the source of leakage. Apply Teflon tape around the pipe thread. Replace if required. Test for water leakage.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.water_tap.04',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.water_tap',
    componentName: 'Water Tap',
    defectId: 'sanitary_fitting.water_tap.04',
    defectDescription: 'Water tap is loose',
    correctiveAction: 'Reinstall the water tap. Make sure it is tightened and firm. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.water_tap.05',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.water_tap',
    componentName: 'Water Tap',
    defectId: 'sanitary_fitting.water_tap.05',
    defectDescription: 'Water tap is rusty',
    correctiveAction: 'Replace with a new water tap. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.water_tap.06',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.water_tap',
    componentName: 'Water Tap',
    defectId: 'sanitary_fitting.water_tap.06',
    defectDescription: 'Water tap water pressure is low',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.01',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.01',
    defectDescription: 'Flush button is not functioning properly',
    correctiveAction:
        'Readjust the flush button installation. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.02',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.02',
    defectDescription:
        'Toilet cistern float is not functioning. Water overflows.',
    correctiveAction: 'Replace with a new toilet cistern float. Make sure water stops at the required level. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.03',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.03',
    defectDescription: 'WC cistern has no water supply',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.04',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.04',
    defectDescription: 'WC cistern inlet pipe is rusty/damaged',
    correctiveAction: 'Replace with a new inlet pipe. Make sure the finishing is good. Test for leakage.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.05',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.05',
    defectDescription: 'WC cistern is chipped/damaged',
    correctiveAction:
        'Replace with a new WC cistern. Test for functionality and leakage.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.06',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.06',
    defectDescription: 'WC cistern is leaking',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.07',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.07',
    defectDescription: 'WC cistern is loose',
    correctiveAction: 'Reinstall the cistern. Make sure it is plugged to the wall, tightened and firm. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.08',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.08',
    defectDescription: 'WC cistern lid is loose',
    correctiveAction: 'Reinstall the cistern lid. Replace if required. Test for functionality',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_cistern.09',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_cistern',
    componentName: 'WC Cistern',
    defectId: 'sanitary_fitting.wc_cistern.09',
    defectDescription: 'WC inlet pipe is leaking',
    correctiveAction: 'Check the source of leakage. Apply Teflon tape around the pipe thread. Replace if required. Test for water leakage.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.01',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.01',
    defectDescription: 'Gap between WC and floor tiles is not sealed off',
    correctiveAction: 'Grout the gap with sealant. Make sure the gap is fully sealed and the finishing is good.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.02',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.02',
    defectDescription: 'Toilet bowl is chipped/damaged/crack',
    correctiveAction:
        'Replace with a new toilet bowl. Test for functionality and leakage.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.03',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.03',
    defectDescription: 'Toilet bowl is clogged/slow draining',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.04',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.04',
    defectDescription: 'Toilet bowl is leaking',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.05',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.05',
    defectDescription: 'Toilet bowl is loose',
    correctiveAction: 'Reinstall the toilet bowl. Make sure it is tightened and firm. Test for leakage and functionality.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.06',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.06',
    defectDescription: 'Toilet bowl seat cover is damaged',
    correctiveAction:
        'Replace with a new toilet bowl seat cover. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.07',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.07',
    defectDescription: 'Toilet bowl is cover is loose',
    correctiveAction: 'Reinstall the toilet bowl seat cover. Make sure it is tightened and firm. Test for functionality.',
  ),
  DefectCatalogueEntry(
    id: 'sanitary_fitting.wc_toilet_bowl.08',
    mainElementId: 'sanitary_fitting',
    mainElementName: 'Sanitary Fitting',
    componentId: 'sanitary_fitting.wc_toilet_bowl',
    componentName: 'WC Toilet Bowl',
    defectId: 'sanitary_fitting.wc_toilet_bowl.08',
    defectDescription: 'Water keeps flowing inside the toilet bowl after pressing the flush button',
    correctiveAction: 'Further investigation must be made by the Developer to check on the source of problem. This problem must be rectified according to the approved method statement from the Consultant/SO.',
  ),
];
